# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   # docker run -d --name nginx nginx
#   - name: nginx
#     image: nginx:stable-perl

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   # docker run -d --name nginx nginx
#   - name: nginx
#     image: nginx:stable-perl
#   tolerations:
#   - key: "hardware"
#     operator: "Equal"
#     value: "gpu"
#     effect: "NoSchedule"


apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl
  nodeSelector:
    hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"